# Setup
title:        Site de démo
tagline:      Une démo pour GitHub Pages
baseurl:      ""
paginate:     1
locale:       "fr"

# About/contact
author:
  name:       Sabrina
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
